### ISSUE TITLE
Base de datos

### ISSUE THREAD

**Issue by a19311044** [a19311044/libroteca#3]
Creación de la base de datos para el almacenamiento de la información de los libros y usuarios.

**Comment by Alfredofigueroasilvas** [comment]
### Elaboración de Base de Datos con SQLite

**Objetivo**: Implementar una base de datos SQLite para gestionar la información de los libros en la aplicación Libroteca.

**Funcionalidades deseadas**:
- Guardar información de libros (título, autor, ISBN, etc.).
- Cargar y mostrar la lista de libros guardados.
- Implementar funcionalidad de búsqueda y filtrado.

**Problemas encontrados**:
- No se pueden guardar algunos campos.
- Dificultad al cargar datos desde la base de datos.

**Estado actual**: En progreso.
